import { useCallback, useEffect, useState } from "react";
import { Check, CircleDot, FileText, LogOut, Plus, RefreshCw, Shield, X } from "lucide-react";

const API = import.meta.env.VITE_API_URL ?? "http://127.0.0.1:8000";
const blank = {title:"",asset_id:"A003",weakness:"",severity:"HIGH",description:"",impact:"",reproduction_steps:"",remediation:"",cve:""};
async function call(path, options={}, token="") { const response=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}}); if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:"Request failed")} return response.json() }

function Auth({onAuth}){
  const [register,setRegister]=useState(false),[form,setForm]=useState({name:"",email:"",password:""}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError("");try{const body=register?form:{email:form.email,password:form.password};onAuth(await call(`/api/auth/${register?"register":"login"}`,{method:"POST",body:JSON.stringify(body)}))}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <main className="auth"><div className="auth-brand"><Shield size={44}/><h1>NovaPay Security</h1><p>Coordinated vulnerability disclosure</p></div><form className="auth-box" onSubmit={submit}><h2>{register?"Create a reporter account":"Sign in to NovaPay"}</h2>{register&&<label>Full name<input required minLength="2" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Email address<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required type="password" minLength={register?10:1} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<p className="flash">{error}</p>}<button className="btn green" disabled={busy}>{busy?"Please wait…":register?"Create account":"Sign in"}</button></form><div className="switch">{register?"Already registered? ":"New researcher? "}<button onClick={()=>{setRegister(!register);setError("")}}>{register?"Sign in":"Create an account"}</button></div></main>
}
function Header({user,logout}){return <header><div className="brand"><Shield size={27}/><strong>NovaPay</strong><span>/</span><b>security-advisories</b></div><div className="account"><em>{user.role==="SECURITY"?"Security team":"Reporter"}</em><i>{user.name[0].toUpperCase()}</i><span>{user.name}</span><button title="Sign out" onClick={logout}><LogOut size={17}/></button></div></header>}
function Status({value}){return <span className={`status ${value.toLowerCase()}`}><CircleDot size={12}/>{value}</span>}
function Severity({value}){return <span className={`severity ${value.toLowerCase()}`}>{value}</span>}

function Editor({token,done,cancel}){
 const [form,setForm]=useState(blank),[error,setError]=useState(""),[busy,setBusy]=useState(false); const change=e=>setForm({...form,[e.target.name]:e.target.value});
 async function submit(e){e.preventDefault();setBusy(true);setError("");try{await call("/api/bug-bounty/reports",{method:"POST",body:JSON.stringify(Object.fromEntries(Object.entries(form).map(([k,v])=>[k,v||null])))},token);done()}catch(err){setError(err.message)}finally{setBusy(false)}}
 return <div className="page narrow"><div className="title"><div><h1>Open a security advisory</h1><p>Provide enough detail for NovaPay to reproduce and assess the issue.</p></div></div><form className="box form" onSubmit={submit}><label>Advisory title *<input required minLength="8" name="title" value={form.title} onChange={change}/></label><div className="cols"><label>Affected asset *<select name="asset_id" value={form.asset_id} onChange={change}>{["A001 Payment Gateway","A002 Payment Database","A003 Authentication API","A004 Customer Portal","A005 HR Portal","A006 Test Server"].map(x=><option key={x} value={x.slice(0,4)}>{x}</option>)}</select></label><label>Severity *<select name="severity" value={form.severity} onChange={change}>{["CRITICAL","HIGH","MEDIUM","LOW"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="cols"><label>Weakness *<input required name="weakness" placeholder="IDOR, AUTH_BYPASS" value={form.weakness} onChange={change}/></label><label>CVE (optional)<input name="cve" value={form.cve} onChange={change}/></label></div><label>Description *<textarea required minLength="20" rows="5" name="description" value={form.description} onChange={change}/></label><label>Impact *<textarea required minLength="10" rows="4" name="impact" value={form.impact} onChange={change}/></label><label>Steps to reproduce *<textarea required minLength="10" rows="7" name="reproduction_steps" value={form.reproduction_steps} onChange={change}/></label><label>Suggested remediation<textarea rows="4" name="remediation" value={form.remediation} onChange={change}/></label>{error&&<p className="flash">{error}</p>}<div className="actions"><button type="button" className="btn" onClick={cancel}>Cancel</button><button className="btn green" disabled={busy}>{busy?"Submitting…":"Submit advisory"}</button></div></form></div>
}
function Detail({report,security,token,reload}){
 const [notes,setNotes]=useState(report.triage_notes||""),[error,setError]=useState(""); async function review(decision){if(notes.trim().length<3)return setError("Add triage notes first.");try{await call(`/api/bug-bounty/reports/${report.report_id}/review`,{method:"PATCH",body:JSON.stringify({decision,triage_notes:notes})},token);reload()}catch(err){setError(err.message)}}
 return <section className="detail"><div className="detail-title"><div><h2>{report.title}</h2><p>#{report.report_id.slice(0,8)} opened by <b>{report.reporter_name}</b></p></div><Status value={report.status}/></div><div className="meta"><div>Asset<b>{report.asset_id}</b></div><div>Weakness<b>{report.weakness}</b></div><div>Severity<Severity value={report.severity}/></div></div><article><h3>Description</h3><p>{report.description}</p><h3>Impact</h3><p>{report.impact}</p><h3>Steps to reproduce</h3><pre>{report.reproduction_steps}</pre>{report.remediation&&<><h3>Suggested remediation</h3><p>{report.remediation}</p></>}{report.triage_notes&&report.status!=="SUBMITTED"&&<aside><h3>Security team response</h3><p>{report.triage_notes}</p><small>Reviewed by {report.reviewed_by}</small></aside>}</article>{security&&report.status==="SUBMITTED"&&<div className="review"><h3>Review advisory</h3><label>Triage notes<textarea rows="3" value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p className="flash">{error}</p>}<div className="actions"><button className="btn red" onClick={()=>review("REJECTED")}><X size={15}/>Reject</button><button className="btn green" onClick={()=>review("ACCEPTED")}><Check size={15}/>Accept as finding</button></div></div>}</section>
}
function Dashboard({auth}){
 const {token,user}=auth,security=user.role==="SECURITY";const [reports,setReports]=useState([]),[selected,setSelected]=useState(null),[filter,setFilter]=useState(security?"SUBMITTED":""),[create,setCreate]=useState(false),[error,setError]=useState(""),[syncing,setSyncing]=useState(false);
 const load=useCallback(async()=>{try{const data=await call(`/api/bug-bounty/reports${filter?`?status=${filter}`:""}`,{},token);setReports(data.reports);setSelected(old=>data.reports.find(r=>r.report_id===old?.report_id)||data.reports[0]||null);setError("")}catch(err){setError(err.message)}},[filter,token]);useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[load]);async function sync(){setSyncing(true);try{await call('/api/ingestion/refresh',{method:'POST'},token);await load()}catch(err){setError(err.message)}finally{setSyncing(false)}} if(create)return <Editor token={token} cancel={()=>setCreate(false)} done={()=>{setCreate(false);load()}}/>;
 return <div className="page"><div className="title"><div><h1>{security?"Security advisories":"Your security reports"}</h1><p>{security?"Review reports and promote validated issues to CRISPR findings. Live updates run every 5 seconds.":"Track reports submitted to NovaPay. Status updates automatically."}</p></div>{security?<button className="btn" onClick={sync} disabled={syncing}><RefreshCw size={16}/>{syncing?'Syncing…':'Sync sources'}</button>:<button className="btn green" onClick={()=>setCreate(true)}><Plus size={16}/>New advisory</button>}</div><nav>{["","SUBMITTED","ACCEPTED","REJECTED"].map(x=><button key={x||"all"} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x||"All"}</button>)}</nav>{error&&<p className="flash">{error}</p>}<div className="workspace"><div className="list"><div className="list-head">{reports.length} advisories</div>{reports.map(r=><button key={r.report_id} className={selected?.report_id===r.report_id?"selected":""} onClick={()=>setSelected(r)}><div><strong>{r.title}</strong><p>#{r.report_id.slice(0,8)} · {r.asset_id}</p></div><Severity value={r.severity}/></button>)}{!reports.length&&<div className="empty"><FileText/><p>No advisories found.</p></div>}</div>{selected?<Detail key={selected.report_id} report={selected} security={security} token={token} reload={load}/>:<div className="empty"><FileText size={36}/><h2>Select an advisory</h2></div>}</div></div>
}
export default function App(){const [auth,setAuth]=useState(()=>{try{return JSON.parse(localStorage.getItem("crispr-auth"))}catch{return null}});function save(data){const value={token:data.access_token,user:data.user};localStorage.setItem("crispr-auth",JSON.stringify(value));setAuth(value)}function logout(){localStorage.removeItem("crispr-auth");setAuth(null)}return auth?<><Header user={auth.user} logout={logout}/><Dashboard auth={auth}/></>:<Auth onAuth={save}/>}
